package com.upgrad.technical.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.validation.annotation.Validated;

import javax.validation.constraints.NotNull;
import java.util.Objects;

@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-04-24T13:07:56.222+05:30")


public class ImageDetailsResponse {
    @JsonProperty("id")
    private int id = Integer.parseInt(null);

    @JsonProperty("image")
    private String image = null;

    @JsonProperty("name")
    private String name = null;

    @JsonProperty("status")
    private String status = null;

    @JsonProperty("description")
    private String description = null;

    public ImageDetailsResponse  id(int id) {
        this.id = id;
        return this;
    }

    /**
     * User identifier in a standard UUID format generated by API backend
     * @return id
     **/
    @ApiModelProperty(required = true, value = "User identifier in a standard UUID format generated by API backend")
    @NotNull


    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public ImageDetailsResponse  name(String name) {
        this.name = name;
        return this;
    }

    /**
     * User identifier in a standard UUID format generated by API backend
     * @return id
     **/
    @ApiModelProperty(required = true, value = "User identifier in a standard UUID format generated by API backend")
    @NotNull


    public String getName() {
        return name;
    }

    public void setId(String name) {
        this.name = name;
    }


    public ImageDetailsResponse  image(String image) {
        this.image = image;
        return this;
    }

    /**
     * Get status
     * @return status
     **/
    @ApiModelProperty(required = true, value = "")
    @NotNull


    public String getImage() {
        return image;
    }

    public void setImage(String status) {
        this.image = image;
    }

    public ImageDetailsResponse status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     * @return status
     **/
    @ApiModelProperty(required = true, value = "")
    @NotNull


    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }


    public ImageDetailsResponse description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get status
     * @return status
     **/
    @ApiModelProperty(required = true, value = "")
    @NotNull


    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ImageDetailsResponse  ImageDetailsResponse  = (ImageDetailsResponse ) o;
        return Objects.equals(this.id, ImageDetailsResponse .id) &&
                Objects.equals(this.image, ImageDetailsResponse .image);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, image);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ImageDetailsResponse  {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    image: ").append(toIndentedString(image)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
